
modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]

modId="overthevoid"
version="${file.jarVersion}"
displayName="OverTheVoid"
description='''

'''

[[dependencies.overthevoid]]
   modId="forge"
   mandatory=true
   versionRange="[40,)" #mandatory
   ordering="NONE"


[[dependencies.overthevoid]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.18.2,1.19)"
   ordering="NONE"
   side="BOTH"
